# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SMB_Link_Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SMB_Link_Demo

  pod 'TOSMBClient', '~> 1.0.5'
  pod 'MobileVLCKit'
  pod 'YYCategories'

end
